### ISSUE TITLE
Box kemajuan studi

### ISSUE THREAD

**Issue by kristt26** [Ocph23/simak.stimik.mobile#3]
Tidak ada nilainya

**Comment by Ocph23** [comment]
Designnya :
![image](https://user-images.githubusercontent.com/8438698/68922186-53d6fb00-07be-11ea-9da5-3c96d1359b87.png)
ada saran ?

**Comment by kristt26** [comment]
kayaknya desainnya sudah mantaplah untuk tampilan androidnya tinggal dibawahnya tambahkan keterangan total sks tempuh dan IPK mahasiswa

**Comment by Ocph23** [comment]
Lihat Profile Tap di photo profile
